[tool.poetry]
name = "fastapi-todo"
version = "0.1.0"
description = "FastAPI Todo App"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]  # 本番環境でも必要なパッケージ
python = "^3.11"
fastapi = "^0.110.0"
uvicorn = { extras = ["standard"], version = "^0.29.0" }
sqlalchemy = "^2.0.29"
asyncpg = "^0.29.0"
alembic = "^1.13.1"
pymysql = "^1.1.1"

[tool.poetry.group.dev.dependencies]  # 開発時だけ必要なパッケージ
pytest = "^8.2.0"
httpx = "^0.27.0"
black = "^24.3.0"
ruff = "^0.4.0"
